version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    commit-message:
      prefix: "[Gradle]"
    reviewers:
      - "doubleangels"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    commit-message:
      prefix: "[Github Actions]"
    reviewers:
      - "doubleangels"
