# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  target-branch: "dev"
  commit-message:
    prefix: "[Gradle]"
  reviewers:
    - "doubleangels"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  target-branch: "dev"
  commit-message:
    prefix: "[Github Actions]"
  reviewers:
    - "doubleangels"
