name: Get localization changes from Crowdin

on:
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: crowdin action
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          localization_branch_name: crowdin
          create_pull_request: true
          pull_request_title: "[Crowdin] Localization updates"
          pull_request_body: "New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)"
          pull_request_base_branch_name: "main"
          token: ${{ secrets.CROWDIN_API_TOKEN }}
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
