name: Development Build Testing

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-gms-flavor:
    if: |
      (github.event_name == 'push' && github.actor != 'dependabot[bot]') ||
      (github.event_name == 'pull_request' && github.actor == 'dependabot[bot]') ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Android build
        uses: ./.github/actions/setup-android-build

      - name: Run Lint
        run: ./gradlew lintGmsRelease
        continue-on-error: false

  build-gms-flavor:
    if: |
      (github.event_name == 'push' && github.actor != 'dependabot[bot]') ||
      (github.event_name == 'pull_request' && github.actor == 'dependabot[bot]') ||
      github.event_name == 'workflow_dispatch'
    needs: lint-gms-flavor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Android build
        uses: ./.github/actions/setup-android-build

      - name: Build GMS Release
        run: ./gradlew assembleGmsRelease
        continue-on-error: false

  lint-foss-flavor:
    if: |
      (github.event_name == 'push' && github.actor != 'dependabot[bot]') ||
      (github.event_name == 'pull_request' && github.actor == 'dependabot[bot]') ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Android build
        uses: ./.github/actions/setup-android-build

      - name: Run Lint
        run: ./gradlew lintFossRelease
        continue-on-error: false

  build-foss-flavor:
    if: |
      (github.event_name == 'push' && github.actor != 'dependabot[bot]') ||
      (github.event_name == 'pull_request' && github.actor == 'dependabot[bot]') ||
      github.event_name == 'workflow_dispatch'
    needs: lint-foss-flavor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Android build
        uses: ./.github/actions/setup-android-build

      - name: Build FOSS Release
        run: ./gradlew assembleFossRelease
        continue-on-error: false
