name: Development Build Testing

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-gms-flavor:
    if: |
      (github.event_name == 'push' && github.actor != 'dependabot[bot]') ||
      (github.event_name == 'pull_request' && github.actor == 'dependabot[bot]') ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Android Environment
        uses: ./.github/actions/setup-android-env

      - name: Run Lint
        run: ./gradlew lintGmsRelease --no-daemon
        continue-on-error: false

      - name: Build GMS Release
        if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
        run: ./gradlew assembleGmsRelease --no-daemon
        continue-on-error: false

  test-foss-flavor:
    if: |
      (github.event_name == 'push' && github.actor != 'dependabot[bot]') ||
      (github.event_name == 'pull_request' && github.actor == 'dependabot[bot]') ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Android Environment
        uses: ./.github/actions/setup-android-env

      - name: Run Lint
        run: ./gradlew lintFossRelease --no-daemon
        continue-on-error: false

      - name: Build FOSS Release
        if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
        run: ./gradlew assembleFossRelease --no-daemon
        continue-on-error: false

  automerge:
    needs:
      [test-gms-flavor, test-foss-flavor]
    if: >
      github.event_name == 'pull_request' &&
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      needs.test-gms-flavor.result == 'success' &&
      needs.test-foss-flavor.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Enable auto-merge for Dependabot PRs
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ github.token }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge
